[options]
AurUrl                 = https://aur.archlinux.org
AurRpcUrl              = https://aur.archlinux.org/rpc?
BuildDir               = ~/.cache/yay
Editor                 = 
EditorFlags            = 
MakepkgBin             = makepkg
MakepkgConf            = 
PacmanBin              = pacman
PacmanConf             = /etc/pacman.conf
ReDownload             = no
AnswerClean            = None
AnswerDiff             = None
AnswerEdit             = 
AnswerUpgrade          = 
GitBin                 = git
GpgBin                 = gpg
GpgFlags               = 
MFlags                 = 
SortBy                 = 
SearchBy               = name-desc
GitFlags               = 
RemoveMake             = yes
SudoBin                = sudo
SudoFlags              = 
RequestSplitN          = 150
CompletionInterval     = 7
MaxConcurrentDownloads = 1
BottomUp               = true
SudoLoop               = true
Devel                  = false
CleanAfter             = false
KeepSrc                = false
Provides               = false
PgpFetch               = true
CleanMenu              = true
DiffMenu               = true
EditMenu               = false
CombinedUpgrade        = true
UseAsk                 = false
BatchInstall           = false
SingleLineResults      = false
SeparateSources        = true
Debug                  = false
Rpc                    = true
DoubleConfirm          = true
ReBuild                = no
